#' Set up emission schedule parameters for EMITIMES file
#'
#' This function defines the parameters for an emission schedule,
#' specifically for hourly emissions over a defined period. It returns
#' a list object containing the schedule details.
#'
#' @param start_datetime The POSIXct datetime object for the start of the
#'   first emission.
#' @param lat Latitude of the emission source.
#' @param lon Longitude of the emission source.
#' @param height Height of the emission source in meters AGL.
#' @param rate Emission rate (e.g., in grams per hour).
#' @param total_emission_hours Total number of hours during which hourly
#'   emissions should occur (e.g., 24).
#' @param emission_duration_hhmm Duration of each individual emission event
#'   in "HHMM" format (e.g., "0100" for 1 hour). Defaults to "0100".
#' @param area Emission area in square meters (0 for point source). Defaults to 0.
#' @param heat Heat release in Watts (0 for non-buoyant). Defaults to 0.
#'
#' @return A list object containing the emission schedule parameters.
#' @export
#' @examples
#' schedule <- set_emissions_schedule(
#'   start_datetime = lubridate::ymd_hm("2023-08-01 00:00", tz = "UTC"),
#'   lat = 51.02,
#'   lon = 3.54,
#'   height = 10.0,
#'   rate = 1.0,
#'   total_emission_hours = 24
#' )
set_emissions_schedule <- function(start_datetime,
                                   lat,
                                   lon,
                                   height,
                                   rate,
                                   total_emission_hours = 24,
                                   emission_duration_hhmm = "0100",
                                   area = 0.0,
                                   heat = 0.0) {

  if (!requireNamespace("lubridate", quietly = TRUE)) {
    stop("Package 'lubridate' needed for this function to work. Please install it.", call. = FALSE)
  }
  if (!requireNamespace("dplyr", quietly = TRUE)) {
    stop("Package 'dplyr' needed for this function to work. Please install it.", call. = FALSE)
  }
   if (!requireNamespace("purrr", quietly = TRUE)) {
    stop("Package 'purrr' needed for this function to work. Please install it.", call. = FALSE)
  }

  # Generate hourly start times
  start_times <- seq(from = start_datetime,
                     by = "hour",
                     length.out = total_emission_hours)

  # Create a data frame representing the emission records
  schedule_df <- tibble::tibble(
    start_time = start_times,
    lat = lat,
    lon = lon,
    height = height,
    rate = rate,
    duration_hhmm = emission_duration_hhmm,
    area = area,
    heat = heat
  )

  # Determine the overall cycle duration (must cover all records)
  # HYSPLIT format seems to be HHHH (zero-padded if needed)
  cycle_duration_hours_val <- ceiling(as.numeric(difftime(max(start_times) + lubridate::hours(as.numeric(substr(emission_duration_hhmm, 1, 2))),
                                                        start_datetime, units = "hours")))
  cycle_duration_hhhh <- sprintf("%04d", cycle_duration_hours_val)


  # Return a list containing schedule details and header info
  schedule_list <- list(
    cycle_start_datetime = start_datetime,
    cycle_duration_hhhh = cycle_duration_hhhh,
    num_records = total_emission_hours,
    schedule_df = schedule_df
  )

  return(schedule_list)
}


#' Write an EMITIMES file
#'
#' Takes a schedule list object created by `set_emissions_schedule`
#' and writes it to a file in the HYSPLIT EMITIMES format.
#'
#' @param schedule A list object generated by `set_emissions_schedule`.
#' @param dir The directory where the EMITIMES file should be written.
#'   Defaults to the current working directory.
#' @param filename The name for the output EMITIMES file. Defaults to
#'   "EMITIMES".
#'
#' @return Invisibly returns the full path to the written file.
#' @export
#' @examples
#' \dontrun{
#' schedule <- set_emissions_schedule(
#'   start_datetime = lubridate::ymd_hm("2023-08-01 00:00", tz = "UTC"),
#'   lat = 51.02,
#'   lon = 3.54,
#'   height = 10.0,
#'   rate = 1.0,
#'   total_emission_hours = 24
#' )
#' write_emittimes_file(schedule, dir = exec_dir, filename = "emissions_hourly.txt")
#' }
write_emittimes_file <- function(schedule, dir = ".", filename = "EMITIMES") {

  if (!dir.exists(dir)) {
    stop("Directory '", dir, "' does not exist.", call. = FALSE)
  }

  output_filepath <- file.path(dir, filename)

  # --- Format Header Lines ---
  # Ref: HYSPLIT User Guide Source [2898], [2902]
  cycle_header <- sprintf("%s %s %d",
                        format(schedule$cycle_start_datetime, "%Y %m %d %H"),
                        schedule$cycle_duration_hhhh,
                        schedule$num_records
                        )
  comment_line <- "EMITIMES file generated by splitr helper function"
  format_line <- "# {YYYY} {MM} {DD} {HH} {MM} {Duration_HHMM} {Lat} {Lon} {Hgt} {Rate} {Area} {Heat}"

  # --- Format Data Records ---
  # Ref: HYSPLIT User Guide Source [2903], [2906]
  emission_records <- purrr::pmap_chr(schedule$schedule_df, function(start_time, lat, lon, height, rate, duration_hhmm, area, heat) {
    sprintf("%s %02d %s %.4f %.4f %.1f %.1e %.1f %.1f",
            format(start_time, "%Y %m %d %H"), # YYYY MM DD HH
            00, # MM (minute start)
            duration_hhmm, # Duration HHMM
            lat, # Lat
            lon, # Lon
            height, # Hgt
            rate, # Rate
            area, # Area
            heat # Heat
           )
  })

  # --- Combine and Write File ---
  all_lines <- c(
    cycle_header,
    comment_line,
    format_line,
    emission_records
  )

  # Write to file
  writeLines(all_lines, con = output_filepath)

  cat("EMITIMES file written to:", output_filepath, "\n")
  cat("remember to add file+path to set_config()!\n")
  invisible(output_filepath) # Return path invisibly like other write functions might
}