# Ensure required packages are loaded in your main script or installed
# library(lubridate)
# library(dplyr)
# library(purrr)
# library(tibble) # Part of tidyverse, implicitly used

#' Set up emission schedule parameters for EMITIMES file
#'
#' This function defines the parameters for an emission schedule,
#' specifically for hourly emissions over a defined period. It returns
#' a list object containing the schedule details.
#'
#' @param start_datetime The POSIXct datetime object for the start of the
#'   first emission.
#' @param lat Latitude of the emission source.
#' @param lon Longitude of the emission source.
#' @param height Height of the emission source in meters AGL.
#' @param rate Emission rate (e.g., in grams per hour).
#' @param total_emission_hours Total number of hours during which hourly
#'   emissions should occur (e.g., 24).
#' @param emission_duration_hhmm Duration of each individual emission event
#'   in "HHMM" format (e.g., "0100" for 1 hour). Defaults to "0100".
#' @param area Emission area in square meters (0 for point source). Defaults to 0.
#' @param heat Heat release in Watts (0 for non-buoyant). Defaults to 0.
#'
#' @return A list object containing the emission schedule parameters.
#' @export
#' @examples
#' schedule <- set_emissions_schedule(
#'   start_datetime = lubridate::ymd_hm("2023-08-01 00:00", tz = "UTC"),
#'   lat = 51.02,
#'   lon = 3.54,
#'   height = 10.0,
#'   rate = 1.0,
#'   total_emission_hours = 24
#' )
set_emissions_schedule <- function(start_datetime,
                                   lat,
                                   lon,
                                   height,
                                   rate,
                                   total_emission_hours = 24,
                                   emission_duration_hhmm = "0100",
                                   area = 0.0,
                                   heat = 0.0) {
  
  # Check for necessary packages
  if (!requireNamespace("lubridate", quietly = TRUE)) {
    stop("Package 'lubridate' needed. Please install it.", call. = FALSE)
  }
  if (!requireNamespace("dplyr", quietly = TRUE)) {
    stop("Package 'dplyr' needed. Please install it.", call. = FALSE)
  }
  if (!requireNamespace("purrr", quietly = TRUE)) {
    stop("Package 'purrr' needed. Please install it.", call. = FALSE)
  }
  if (!requireNamespace("tibble", quietly = TRUE)) {
    stop("Package 'tibble' needed. Please install it.", call. = FALSE)
  }
  
  # Generate hourly start times
  start_times <- seq(from = start_datetime,
                     by = "hour",
                     length.out = total_emission_hours)
  
  # Create a data frame representing the emission records
  schedule_df <- tibble::tibble(
    start_time = start_times,
    lat = lat,
    lon = lon,
    height = height,
    rate = rate,
    duration_hhmm = emission_duration_hhmm,
    area = area,
    heat = heat
  )
  
  # Return a list containing schedule details
  # Cycle header info will be generated per record in the write function
  schedule_list <- list(
    schedule_df = schedule_df
  )
  
  return(schedule_list)
}


#' Write an EMITIMES file with Multiple Cycles
#'
#' Takes a schedule list object created by `set_emissions_schedule`
#' and writes it to a file in the HYSPLIT EMITIMES format, creating
#' a separate cycle header for each emission record. This structure is
#' needed when defining multiple emission times for a single source/pollutant
#' in the CONTROL file.
#'
#' @param schedule A list object generated by `set_emissions_schedule`.
#' @param dir The directory where the EMITIMES file should be written.
#'   Defaults to the current working directory.
#' @param filename The name for the output EMITIMES file. Defaults to
#'   "EMITIMES".
#'
#' @return Invisibly returns the full path to the written file.
#' @export
#' @examples
#' \dontrun{
#' schedule <- set_emissions_schedule(
#'   start_datetime = lubridate::ymd_hm("2023-08-01 00:00", tz = "UTC"),
#'   lat = 51.02,
#'   lon = 3.54,
#'   height = 10.0,
#'   rate = 1.0,
#'   total_emission_hours = 24
#' )
#' # Assuming exec_dir is defined
#' write_emittimes_file_multi_cycle(schedule, dir = exec_dir, filename = "emissions_multi_cycle.txt")
#' }
write_emittimes_file_multi_cycle <- function(schedule, dir = ".", filename = "EMITIMES") {
  
  # Check for necessary packages
  if (!requireNamespace("purrr", quietly = TRUE)) {
    stop("Package 'purrr' needed. Please install it.", call. = FALSE)
  }
  
  if (!dir.exists(dir)) {
    # Attempt to create the directory if it doesn't exist
    dir.create(dir, recursive = TRUE, showWarnings = FALSE)
    if (!dir.exists(dir)){
      stop("Directory '", dir, "' does not exist and could not be created.", call. = FALSE)
    }
  }
  
  output_filepath <- file.path(dir, filename)
  
  # --- Format Header Lines ---
  comment_line <- "EMITIMES file generated by R script (multi-cycle format)"
  format_line <- "# {YYYY} {MM} {DD} {HH} {MM} {Duration_HHMM} {Lat} {Lon} {Hgt} {Rate} {Area} {Heat}"
  
  # --- Generate lines with cycle header per record ---
  all_lines <- list()
  all_lines[[1]] <- comment_line
  all_lines[[2]] <- format_line
  
  if (nrow(schedule$schedule_df) > 0) {
    for (i in 1:nrow(schedule$schedule_df)) {
      record_data <- schedule$schedule_df[i,]
      start_time <- record_data$start_time[[1]] # Use [[1]] to get the value
      
      # Cycle Header: Start Time YYYY MM DD HH, Duration (e.g., 0001 hr), Num Records (always 1)
      # Ref: HYSPLIT User Guide Source [2898], [2902]
      # Using a cycle duration of 1 hour (0001) - adjust if emissions overlap etc.
      cycle_header <- sprintf("%s %s %d",
                              format(start_time, "%Y %m %d %H"),
                              "0001", # Cycle duration is 1 hour
                              1       # Number of records in this cycle is 1
      )
      
      # Data Record
      # Ref: HYSPLIT User Guide Source [2903], [2906]
      data_record <- sprintf("%s %02d %s %.4f %.4f %.1f %.1e %.1f %.1f",
                             format(start_time, "%Y %m %d %H"), # Emission Start YYYY MM DD HH
                             00, # MM (minute start)
                             record_data$duration_hhmm, # Duration HHMM (e.g., 0100)
                             record_data$lat,
                             record_data$lon,
                             record_data$height,
                             record_data$rate,
                             record_data$area,
                             record_data$heat
      )
      
      # Add cycle header and data record to the list
      all_lines[[length(all_lines) + 1]] <- cycle_header
      all_lines[[length(all_lines) + 1]] <- data_record
    }
  } else {
    warning("No emission records found in the schedule to write.", call.=FALSE)
    # Write empty file with headers? Or just return? Let's write headers.
    all_lines <- c(comment_line, format_line)
  }
  
  
  # --- Write File ---
  # Use tryCatch for better error handling during file writing
  write_result <- tryCatch({
    writeLines(unlist(all_lines), con = output_filepath)
    TRUE # Indicate success
  }, error = function(e) {
    warning("Failed to write EMITIMES file to '", output_filepath, "'. Error: ", e$message, call. = FALSE)
    FALSE # Indicate failure
  })
  
  if(write_result){
    #cat("Multi-cycle EMITIMES file written to:", output_filepath, "\n")
  }
  
  invisible(output_filepath) # Return path invisibly
}