#' Write an EMITIMES file with Multiple Cycles
#'
#' Takes a schedule list object created by `set_emissions_schedule`
#' and writes it to a file in the HYSPLIT EMITIMES format, creating
#' a separate cycle header for each emission record.
#'
#' @param schedule A list object generated by `set_emissions_schedule`.
#' @param dir The directory where the EMITIMES file should be written.
#'   Defaults to the current working directory.
#' @param filename The name for the output EMITIMES file. Defaults to
#'   "EMITIMES_multicycle.txt".
#'
#' @return Invisibly returns the full path to the written file.
#' @export
#' @examples
#' \dontrun{
#' schedule <- set_emissions_schedule(
#'   start_datetime = lubridate::ymd_hm("2023-08-01 00:00", tz = "UTC"),
#'   lat = 51.02,
#'   lon = 3.54,
#'   height = 10.0,
#'   rate = 1.0,
#'   total_emission_hours = 24
#' )
#' write_EMITIMES_file_multi_cycle(schedule, dir = exec_dir, filename = "EMITIMES")
#' }
write_EMITIMES_file_multi_cycle <- function(schedule, dir = ".", filename = "EMITIMES") {
  
  if (!dir.exists(dir)) {
    stop("Directory '", dir, "' does not exist.", call. = FALSE)
  }
  if (!requireNamespace("purrr", quietly = TRUE)) {
    stop("Package 'purrr' needed for this function to work. Please install it.", call. = FALSE)
  }
  
  output_filepath <- file.path(dir, filename)
  
  # --- Format Header Lines ---
  comment_line <- "EMITIMES file generated by R script (multi-cycle format)"
  format_line <- "# {YYYY} {MM} {DD} {HH} {MM} {Duration_HHMM} {Lat} {Lon} {Hgt} {Rate} {Area} {Heat}"
  
  # --- Generate lines with cycle header per record ---
  all_lines <- list()
  all_lines[[1]] <- comment_line
  all_lines[[2]] <- format_line
  
  for (i in 1:nrow(schedule$schedule_df)) {
    record_data <- schedule$schedule_df[i,]
    start_time <- record_data$start_time[[1]]
    
    # Cycle Header: Start Time YYYY MM DD HH, Duration (e.g., 0001 hr), Num Records (always 1)
    # Ref: HYSPLIT User Guide Source [2898], [2902]
    cycle_header <- sprintf("%s %s %d",
                            format(start_time, "%Y %m %d %H"),
                            "0001", # Cycle duration is 1 hour
                            1       # Number of records in this cycle is 1
    )
    
    # Data Record
    # Ref: HYSPLIT User Guide Source [2903], [2906]
    data_record <- sprintf("%s %02d %s %.4f %.4f %.1f %.1e %.1f %.1f",
                           format(start_time, "%Y %m %d %H"), # Emission Start YYYY MM DD HH
                           00, # MM (minute start)
                           record_data$duration_hhmm, # Duration HHMM (e.g., 0100)
                           record_data$lat,
                           record_data$lon,
                           record_data$height,
                           record_data$rate,
                           record_data$area,
                           record_data$heat
    )
    
    # Add cycle header and data record to the list
    all_lines[[length(all_lines) + 1]] <- cycle_header
    all_lines[[length(all_lines) + 1]] <- data_record
  }
  
  # --- Write File ---
  writeLines(unlist(all_lines), con = output_filepath)
  
  #cat("Multi-cycle EMITIMES file written to:", output_filepath, "\n")
  invisible(output_filepath)
}

# --- Example Usage ---
# Ensure set_emissions_schedule is defined/sourced first

# Define schedule (as before)
# emission_schedule <- set_emissions_schedule(...)

# Write the multi-cycle file
# EMITIMES_multi_filename <- "EMITIMES"
# write_EMITIMES_file_multi_cycle(
#   schedule = emission_schedule,
#   dir = exec_dir,
#   filename = EMITIMES_multi_filename
# )

# Then use EMITIMES_multi_filename in set_config:
# hysplit_config <- set_config(ichem = 5, efile = EMITIMES_multi_filename)
# ... run_model ...